import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../app/routes.dart';
import '../core/responsive.dart';
import '../models/session_response.dart';
import '../theme/app_colors.dart';
import '../theme/app_spacing.dart';
import '../theme/app_theme.dart';
import '../widgets/error_view.dart';
import '../widgets/readiness_score_card.dart';
import '../widgets/section_card.dart';

// ── Parsed data classes ───────────────────────────────────────────────────────

class _Phase {
  final String phase;
  final String duration;
  final String approach;

  _Phase({required this.phase, required this.duration, required this.approach});

  factory _Phase.fromMap(Map<String, dynamic> m) => _Phase(
        phase: m['phase'] as String? ?? '',
        duration: m['duration'] as String? ?? '',
        approach: m['approach'] as String? ?? '',
      );
}

class _Objection {
  final String objection;
  final String response;
  final String severity;
  final bool criticRevised;

  _Objection({
    required this.objection,
    required this.response,
    required this.severity,
    required this.criticRevised,
  });

  factory _Objection.fromMap(Map<String, dynamic> m) => _Objection(
        objection: m['objection'] as String? ?? '',
        response: m['response'] as String? ?? '',
        severity: m['severity'] as String? ?? 'MEDIUM',
        criticRevised: m['criticRevised'] as bool? ?? false,
      );
}

// ── Screen ────────────────────────────────────────────────────────────────────

class FinalReportScreen extends StatefulWidget {
  final SessionResponse session;

  const FinalReportScreen({super.key, required this.session});

  @override
  State<FinalReportScreen> createState() => _FinalReportScreenState();
}

class _FinalReportScreenState extends State<FinalReportScreen> {
  final Set<int> _expandedObjections = {0, 1, 2};

  // Parsed from JSON once
  late final List<_Phase> _phases;
  late final List<String> _questions;
  late final List<_Objection> _objections;
  late final List<String> _dos;
  late final List<String> _donts;
  late final List<String> _nextSteps;

  @override
  void initState() {
    super.initState();
    final report = widget.session.finalReport;
    _phases = _parseList(
        report?.conversationFlowJson, (m) => _Phase.fromMap(m));
    _questions = _parseStringList(report?.questionsJson);
    _objections = _parseList(
        report?.objectionResponsesJson, (m) => _Objection.fromMap(m));
    _nextSteps = _parseStringList(report?.nextStepsJson);

    final doAndDont = _parseMap(report?.doAndDontJson);
    _dos = _toStringList(doAndDont['dos']);
    _donts = _toStringList(doAndDont['donts']);
  }

  static List<T> _parseList<T>(
      String? json, T Function(Map<String, dynamic>) fn) {
    if (json == null) return [];
    try {
      return (jsonDecode(json) as List<dynamic>)
          .map((e) => fn(e as Map<String, dynamic>))
          .toList();
    } catch (_) {
      return [];
    }
  }

  static List<String> _parseStringList(String? json) {
    if (json == null) return [];
    try {
      return (jsonDecode(json) as List<dynamic>)
          .map((e) => e.toString())
          .toList();
    } catch (_) {
      return [];
    }
  }

  static Map<String, dynamic> _parseMap(String? json) {
    if (json == null) return {};
    try {
      return jsonDecode(json) as Map<String, dynamic>;
    } catch (_) {
      return {};
    }
  }

  static List<String> _toStringList(dynamic v) {
    if (v is List) return v.map((e) => e.toString()).toList();
    return [];
  }

  void _copyReport() {
    final report = widget.session.finalReport;
    final buf = StringBuffer();
    buf.writeln('MEETING BRIEF — ${widget.session.organizationName}');
    buf.writeln(
        'Generated by MeetWise · ${widget.session.agentRuns.length} Agents · '
        'Readiness: ${((report?.overallConfidence ?? 0) * 100).toStringAsFixed(0)}%');
    buf.writeln();

    if (report?.executiveBrief != null) {
      buf.writeln('EXECUTIVE BRIEF');
      buf.writeln(report!.executiveBrief);
      buf.writeln();
    }

    if (_phases.isNotEmpty) {
      buf.writeln('CONVERSATION FLOW');
      for (var i = 0; i < _phases.length; i++) {
        final p = _phases[i];
        buf.writeln('${i + 1}. ${p.phase} (${p.duration})');
        buf.writeln('   ${p.approach}');
      }
      buf.writeln();
    }

    if (_questions.isNotEmpty) {
      buf.writeln('QUESTIONS TO ASK');
      for (var i = 0; i < _questions.length; i++) {
        buf.writeln('${i + 1}. ${_questions[i]}');
      }
      buf.writeln();
    }

    if (_objections.isNotEmpty) {
      buf.writeln('OBJECTIONS & RESPONSES');
      for (final o in _objections) {
        buf.writeln('Q: ${o.objection}');
        buf.writeln('A: ${o.response}');
        buf.writeln();
      }
    }

    if (_dos.isNotEmpty) {
      buf.writeln('DO');
      for (final d in _dos) {
        buf.writeln('✓ $d');
      }
      buf.writeln();
    }

    if (_donts.isNotEmpty) {
      buf.writeln("DON'T");
      for (final d in _donts) {
        buf.writeln('✗ $d');
      }
      buf.writeln();
    }

    if (_nextSteps.isNotEmpty) {
      buf.writeln('NEXT STEPS');
      for (var i = 0; i < _nextSteps.length; i++) {
        buf.writeln('${i + 1}. ${_nextSteps[i]}');
      }
    }

    Clipboard.setData(ClipboardData(text: buf.toString()));

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Row(
          children: [
            Icon(Icons.check_circle_outline, color: Colors.white, size: 16),
            SizedBox(width: AppSpacing.sm),
            Text('Report copied to clipboard'),
          ],
        ),
        duration: Duration(seconds: 2),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final report = widget.session.finalReport;
    if (report == null) {
      return Scaffold(
        appBar: AppBar(
          title: Text('Meeting Brief — ${widget.session.organizationName}'),
        ),
        body: ErrorView(
          compact: false,
          isError: false,
          icon: Icons.article_outlined,
          title: 'Report Not Ready',
          message:
              'The final meeting brief has not been generated yet. '
              'The agent pipeline may still be running.\n\n'
              'Check the Agent Trace view for pipeline status.',
          onRetry: () => Navigator.pushReplacementNamed(
              context, Routes.trace,
              arguments: widget.session),
          retryLabel: 'View Agent Trace',
          onSecondary: () => Navigator.pop(context),
          secondaryLabel: 'Go Back',
        ),
      );
    }

    return Scaffold(
      appBar: _buildAppBar(context),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            _ReadinessHero(session: widget.session, onCopy: _copyReport),
            Padding(
              padding: Responsive.pagePadding(context),
              child: Responsive.centered(
                context,
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (report.executiveBrief != null) ...[
                      _ExecutiveBriefCard(brief: report.executiveBrief!),
                      AppSpacing.gapLg,
                    ],
                    if (_phases.isNotEmpty) ...[
                      _ConversationFlowCard(phases: _phases),
                      AppSpacing.gapLg,
                    ],
                    if (_questions.isNotEmpty) ...[
                      _QuestionsCard(questions: _questions),
                      AppSpacing.gapLg,
                    ],
                    if (_objections.isNotEmpty) ...[
                      _ObjectionsCard(
                        objections: _objections,
                        expanded: _expandedObjections,
                        onToggle: (i) => setState(() =>
                            _expandedObjections.contains(i)
                                ? _expandedObjections.remove(i)
                                : _expandedObjections.add(i)),
                      ),
                      AppSpacing.gapLg,
                    ],
                    if (_dos.isNotEmpty || _donts.isNotEmpty) ...[
                      _DoAndDontCard(dos: _dos, donts: _donts),
                      AppSpacing.gapLg,
                    ],
                    if (_nextSteps.isNotEmpty) ...[
                      _NextStepsCard(steps: _nextSteps),
                      AppSpacing.gapLg,
                    ],
                    _AgentFooter(session: widget.session),
                    AppSpacing.gapXl,
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  PreferredSizeWidget _buildAppBar(BuildContext context) => AppBar(
        title: Text('Meeting Brief — ${widget.session.organizationName}'),
        actions: [
          TextButton.icon(
            onPressed: () => Navigator.pushNamed(
                context, Routes.trace,
                arguments: widget.session),
            icon: const Icon(Icons.account_tree_outlined, size: 16),
            label: const Text('Agent Trace'),
          ),
          IconButton(
            onPressed: _copyReport,
            tooltip: 'Copy report',
            icon: const Icon(Icons.copy_outlined, size: 18),
          ),
          const SizedBox(width: AppSpacing.sm),
        ],
      );
}

// ── Readiness hero ────────────────────────────────────────────────────────────

class _ReadinessHero extends StatelessWidget {
  final SessionResponse session;
  final VoidCallback onCopy;

  const _ReadinessHero({required this.session, required this.onCopy});

  @override
  Widget build(BuildContext context) {
    final report = session.finalReport!;
    final conf = report.overallConfidence;
    final geminiCount = session.agentRuns.where((r) => r.usedGemini).length;
    final ruleCount = session.agentRuns.length - geminiCount;
    final isMobile = Responsive.isMobile(context);
    final criticRevised = session.agentRuns
        .any((r) => r.agentName == 'FinalSynthesisAgent');

    return Container(
      decoration: AppTheme.heroDecoration.copyWith(
        borderRadius: BorderRadius.zero,
      ),
      padding: EdgeInsets.symmetric(
        horizontal: isMobile ? AppSpacing.lg : AppSpacing.xxxl,
        vertical: isMobile ? AppSpacing.xxl : AppSpacing.xxxl,
      ),
      child: Responsive.centered(
        context,
        isMobile
            ? Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _HeroLeft(
                      session: session,
                      geminiCount: geminiCount,
                      ruleCount: ruleCount,
                      criticRevised: criticRevised,
                      onCopy: onCopy),
                  AppSpacing.gapXl,
                  Center(
                      child: ReadinessScoreCard(score: conf, size: 140)),
                ],
              )
            : Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Expanded(
                    child: _HeroLeft(
                        session: session,
                        geminiCount: geminiCount,
                        ruleCount: ruleCount,
                        criticRevised: criticRevised,
                        onCopy: onCopy),
                  ),
                  AppSpacing.hGapLg,
                  ReadinessScoreCard(score: conf, size: 160),
                ],
              ),
      ),
    );
  }
}

class _HeroLeft extends StatelessWidget {
  final SessionResponse session;
  final int geminiCount;
  final int ruleCount;
  final bool criticRevised;
  final VoidCallback onCopy;

  const _HeroLeft({
    required this.session,
    required this.geminiCount,
    required this.ruleCount,
    required this.criticRevised,
    required this.onCopy,
  });

  @override
  Widget build(BuildContext context) {
    final isMobile = Responsive.isMobile(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Label chip
        Container(
          padding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.sm, vertical: AppSpacing.xs),
          decoration: BoxDecoration(
            color: Colors.white.withValues(alpha: 0.15),
            borderRadius: AppSpacing.roundedPill,
            border:
                Border.all(color: Colors.white.withValues(alpha: 0.3)),
          ),
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.article_rounded, color: Colors.white, size: 11),
              SizedBox(width: AppSpacing.xs),
              Text(
                'MEETING BRIEF  ·  MeetWise',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.3,
                ),
              ),
            ],
          ),
        ),
        AppSpacing.gapMd,

        // Org name
        Text(
          session.organizationName,
          style: TextStyle(
            color: Colors.white,
            fontSize: isMobile ? 26 : 36,
            fontWeight: FontWeight.w800,
            letterSpacing: -1.5,
            height: 1.1,
          ),
        ),
        const SizedBox(height: AppSpacing.xs),
        Text(
          [
            if (session.stakeholderRole != null) session.stakeholderRole!,
            if (session.meetingObjective != null) session.meetingObjective!,
          ].join('  ·  '),
          style: TextStyle(
            color: Colors.white.withValues(alpha: 0.8),
            fontSize: 14,
            height: 1.4,
          ),
        ),
        AppSpacing.gapLg,

        // Stats chips row
        Wrap(
          spacing: AppSpacing.sm,
          runSpacing: AppSpacing.xs,
          children: [
            _HeroChip(
                '${session.agentRuns.length} Agents',
                Icons.smart_toy_outlined),
            _HeroChip(
                '${session.traces.length} Traces',
                Icons.account_tree_outlined),
            _HeroChip(
                '$geminiCount Gemini + $ruleCount Rule-based',
                Icons.auto_awesome),
            if (criticRevised)
              _HeroChip(
                  'Critic Validated', Icons.fact_check_outlined,
                  success: true),
          ],
        ),
        AppSpacing.gapLg,

        // Per-agent confidence mini-bars
        ...session.agentRuns.map((run) => Padding(
              padding: const EdgeInsets.only(bottom: AppSpacing.xs),
              child: _AgentBar(run: run),
            )),
        AppSpacing.gapLg,

        // Action buttons
        Wrap(
          spacing: AppSpacing.sm,
          runSpacing: AppSpacing.sm,
          children: [
            OutlinedButton.icon(
              onPressed: () => Navigator.pushNamed(
                  context, Routes.trace,
                  arguments: session),
              icon: const Icon(Icons.account_tree_outlined, size: 16),
              label: const Text('View Agent Trace'),
              style: OutlinedButton.styleFrom(
                foregroundColor: Colors.white,
                side: BorderSide(
                    color: Colors.white.withValues(alpha: 0.5)),
                padding: const EdgeInsets.symmetric(
                    horizontal: AppSpacing.md, vertical: AppSpacing.smMd),
                textStyle: const TextStyle(
                    fontSize: 13, fontWeight: FontWeight.w600),
                minimumSize: const Size(0, 40),
              ),
            ),
            FilledButton.icon(
              onPressed: onCopy,
              icon: const Icon(Icons.copy_outlined, size: 16),
              label: const Text('Copy Report'),
              style: FilledButton.styleFrom(
                backgroundColor: Colors.white,
                foregroundColor: AppColors.brand,
                padding: const EdgeInsets.symmetric(
                    horizontal: AppSpacing.md, vertical: AppSpacing.smMd),
                textStyle: const TextStyle(
                    fontSize: 13, fontWeight: FontWeight.w600),
                minimumSize: const Size(0, 40),
              ),
            ),
          ],
        ),
      ],
    );
  }
}

class _HeroChip extends StatelessWidget {
  final String label;
  final IconData icon;
  final bool success;

  const _HeroChip(this.label, this.icon, {this.success = false});

  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.symmetric(
            horizontal: AppSpacing.sm, vertical: AppSpacing.xs),
        decoration: BoxDecoration(
          color: success
              ? AppColors.success.withValues(alpha: 0.2)
              : Colors.white.withValues(alpha: 0.15),
          borderRadius: AppSpacing.roundedPill,
          border: Border.all(
            color: success
                ? AppColors.success.withValues(alpha: 0.5)
                : Colors.white.withValues(alpha: 0.3),
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, color: Colors.white, size: 11),
            const SizedBox(width: AppSpacing.xs),
            Text(
              label,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 11,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      );
}

class _AgentBar extends StatelessWidget {
  final AgentRun run;

  const _AgentBar({required this.run});

  @override
  Widget build(BuildContext context) {
    final conf = run.confidenceScore;
    final short = run.displayName.split(' ').first;
    return Row(
      children: [
        SizedBox(
          width: 68,
          child: Text(
            short,
            style: TextStyle(
              color: Colors.white.withValues(alpha: 0.75),
              fontSize: 11,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Expanded(
          child: ClipRRect(
            borderRadius: AppSpacing.roundedPill,
            child: LinearProgressIndicator(
              value: conf,
              minHeight: 5,
              backgroundColor: Colors.white.withValues(alpha: 0.15),
              valueColor: AlwaysStoppedAnimation(
                  Colors.white.withValues(alpha: 0.85)),
            ),
          ),
        ),
        const SizedBox(width: AppSpacing.sm),
        SizedBox(
          width: 30,
          child: Text(
            '${(conf * 100).toStringAsFixed(0)}%',
            textAlign: TextAlign.right,
            style: TextStyle(
              color: Colors.white.withValues(alpha: 0.9),
              fontSize: 11,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
      ],
    );
  }
}

// ── Executive brief ───────────────────────────────────────────────────────────

class _ExecutiveBriefCard extends StatelessWidget {
  final String brief;

  const _ExecutiveBriefCard({required this.brief});

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      icon: Icons.summarize_outlined,
      iconColor: AppColors.brand,
      iconBg: AppColors.brandSubtle,
      title: 'Executive Brief',
      subtitle: 'AI-synthesised by FinalSynthesisAgent · Critic revision applied',
      child: Container(
        padding: AppSpacing.cardPadding,
        decoration: AppTheme.brandSurface,
        child: Text(
          brief,
          style: const TextStyle(
            fontSize: 14,
            color: AppColors.textPrimary,
            height: 1.7,
          ),
        ),
      ),
    );
  }
}

// ── Conversation flow ─────────────────────────────────────────────────────────

class _ConversationFlowCard extends StatelessWidget {
  final List<_Phase> phases;

  const _ConversationFlowCard({required this.phases});

  // Total minutes for the overall duration indicator
  int get _totalMinutes {
    int total = 0;
    for (final p in phases) {
      final match = RegExp(r'(\d+)').firstMatch(p.duration);
      if (match != null) total += int.tryParse(match.group(1)!) ?? 0;
    }
    return total;
  }

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      icon: Icons.timeline_outlined,
      iconColor: AppColors.accent,
      iconBg: AppColors.accentSubtle,
      title: 'Conversation Flow',
      subtitle: '${phases.length} phases  ·  ~$_totalMinutes minutes',
      child: Column(
        children: [
          for (var i = 0; i < phases.length; i++)
            _PhaseRow(
                phase: phases[i], index: i, isLast: i == phases.length - 1),
        ],
      ),
    );
  }
}

class _PhaseRow extends StatelessWidget {
  final _Phase phase;
  final int index;
  final bool isLast;

  const _PhaseRow(
      {required this.phase, required this.index, required this.isLast});

  @override
  Widget build(BuildContext context) {
    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Timeline column
          SizedBox(
            width: 32,
            child: Column(
              children: [
                Container(
                  width: 28,
                  height: 28,
                  decoration: BoxDecoration(
                    color: index == 0
                        ? AppColors.accent
                        : AppColors.accentSubtle,
                    shape: BoxShape.circle,
                    border: Border.all(
                      color: AppColors.accent,
                      width: index == 0 ? 0 : 1.5,
                    ),
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    '${index + 1}',
                    style: TextStyle(
                      color: index == 0
                          ? Colors.white
                          : AppColors.accent,
                      fontSize: 12,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
                if (!isLast)
                  Expanded(
                    child: Container(
                      width: 2,
                      color: AppColors.outline,
                      margin: const EdgeInsets.symmetric(vertical: 4),
                    ),
                  ),
              ],
            ),
          ),
          AppSpacing.hGapMd,
          // Content
          Expanded(
            child: Padding(
              padding: EdgeInsets.only(
                  bottom: isLast ? 0 : AppSpacing.lg),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          phase.phase,
                          style: const TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w700,
                            color: AppColors.textPrimary,
                          ),
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: AppSpacing.sm, vertical: 2),
                        decoration: BoxDecoration(
                          color: AppColors.accentSubtle,
                          borderRadius: AppSpacing.roundedPill,
                        ),
                        child: Text(
                          phase.duration,
                          style: const TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                            color: AppColors.accent,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Text(
                    phase.approach,
                    style: const TextStyle(
                      fontSize: 13,
                      color: AppColors.textSecondary,
                      height: 1.5,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Questions to ask ──────────────────────────────────────────────────────────

class _QuestionsCard extends StatelessWidget {
  final List<String> questions;

  const _QuestionsCard({required this.questions});

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      icon: Icons.help_outline_rounded,
      iconColor: AppColors.brand,
      iconBg: AppColors.brandSubtle,
      title: 'Questions to Ask',
      subtitle: '${questions.length} questions · Calibrated to CEO decision lens',
      child: Column(
        children: [
          for (var i = 0; i < questions.length; i++)
            _QuestionRow(question: questions[i], index: i),
        ],
      ),
    );
  }
}

class _QuestionRow extends StatelessWidget {
  final String question;
  final int index;

  const _QuestionRow({required this.question, required this.index});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: AppSpacing.sm),
      padding: AppSpacing.cardPadding,
      decoration: BoxDecoration(
        color: AppColors.surfacePage,
        borderRadius: AppSpacing.roundedMd,
        border: const Border.fromBorderSide(
            BorderSide(color: AppColors.outline)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 22,
            height: 22,
            decoration: const BoxDecoration(
              color: AppColors.brandSubtle,
              shape: BoxShape.circle,
            ),
            alignment: Alignment.center,
            child: Text(
              '${index + 1}',
              style: const TextStyle(
                fontSize: 11,
                fontWeight: FontWeight.w800,
                color: AppColors.brand,
              ),
            ),
          ),
          AppSpacing.hGapMd,
          Expanded(
            child: Text(
              question,
              style: const TextStyle(
                fontSize: 13,
                color: AppColors.textPrimary,
                height: 1.5,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Objections & responses ────────────────────────────────────────────────────

class _ObjectionsCard extends StatelessWidget {
  final List<_Objection> objections;
  final Set<int> expanded;
  final void Function(int) onToggle;

  const _ObjectionsCard({
    required this.objections,
    required this.expanded,
    required this.onToggle,
  });

  int get _highCount =>
      objections.where((o) => o.severity == 'HIGH').length;

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      icon: Icons.shield_outlined,
      iconColor: AppColors.warning,
      iconBg: AppColors.warningLight,
      title: 'Objections & Responses',
      subtitle:
          '${objections.length} predicted · $_highCount HIGH severity · Tap to expand',
      child: Column(
        children: [
          for (var i = 0; i < objections.length; i++)
            _ObjectionItem(
              objection: objections[i],
              index: i,
              isExpanded: expanded.contains(i),
              onToggle: () => onToggle(i),
            ),
        ],
      ),
    );
  }
}

class _ObjectionItem extends StatelessWidget {
  final _Objection objection;
  final int index;
  final bool isExpanded;
  final VoidCallback onToggle;

  const _ObjectionItem({
    required this.objection,
    required this.index,
    required this.isExpanded,
    required this.onToggle,
  });

  Color get _severityFg =>
      objection.severity == 'HIGH' ? AppColors.danger : AppColors.warning;

  Color get _severityBg =>
      objection.severity == 'HIGH'
          ? AppColors.dangerLight
          : AppColors.warningLight;

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 180),
      margin: const EdgeInsets.only(bottom: AppSpacing.sm),
      decoration: BoxDecoration(
        color: isExpanded ? _severityBg : AppColors.surfacePage,
        borderRadius: AppSpacing.roundedMd,
        border: Border.all(
          color: isExpanded
              ? _severityFg.withValues(alpha: 0.3)
              : AppColors.outline,
        ),
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Objection header (always visible)
          InkWell(
            onTap: onToggle,
            child: Padding(
              padding: AppSpacing.cardPadding,
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.warning_amber_rounded,
                      color: _severityFg, size: 18),
                  AppSpacing.hGapSm,
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: AppSpacing.sm, vertical: 1),
                              decoration: BoxDecoration(
                                color: _severityBg,
                                borderRadius: AppSpacing.roundedPill,
                                border: Border.all(
                                    color: _severityFg
                                        .withValues(alpha: 0.4)),
                              ),
                              child: Text(
                                objection.severity,
                                style: TextStyle(
                                    fontSize: 9,
                                    fontWeight: FontWeight.w800,
                                    color: _severityFg),
                              ),
                            ),
                            if (objection.criticRevised) ...[
                              AppSpacing.hGapSm,
                              Container(
                                padding: const EdgeInsets.symmetric(
                                    horizontal: AppSpacing.sm, vertical: 1),
                                decoration: BoxDecoration(
                                  color: AppColors.successLight,
                                  borderRadius: AppSpacing.roundedPill,
                                  border: Border.all(
                                      color: AppColors.success
                                          .withValues(alpha: 0.4)),
                                ),
                                child: const Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Icon(Icons.fact_check_outlined,
                                        size: 9,
                                        color: AppColors.success),
                                    SizedBox(width: 2),
                                    Text(
                                      'Critic Revised',
                                      style: TextStyle(
                                          fontSize: 9,
                                          fontWeight: FontWeight.w700,
                                          color: AppColors.success),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ],
                        ),
                        const SizedBox(height: AppSpacing.xs),
                        Text(
                          objection.objection,
                          style: const TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                            color: AppColors.textPrimary,
                            height: 1.4,
                          ),
                        ),
                      ],
                    ),
                  ),
                  AppSpacing.hGapSm,
                  Icon(
                    isExpanded
                        ? Icons.expand_less_rounded
                        : Icons.expand_more_rounded,
                    color: AppColors.textMuted,
                    size: 20,
                  ),
                ],
              ),
            ),
          ),

          // Response (only when expanded)
          if (isExpanded) ...[
            const Divider(height: 1),
            Padding(
              padding: AppSpacing.cardPadding,
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Icon(Icons.check_circle_outline,
                      color: AppColors.success, size: 18),
                  AppSpacing.hGapSm,
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'RESPONSE',
                          style: TextStyle(
                            fontSize: 10,
                            fontWeight: FontWeight.w700,
                            color: AppColors.success,
                            letterSpacing: 0.5,
                          ),
                        ),
                        const SizedBox(height: AppSpacing.xs),
                        Text(
                          objection.response,
                          style: const TextStyle(
                            fontSize: 13,
                            color: AppColors.textPrimary,
                            height: 1.55,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ── Do & Don't ────────────────────────────────────────────────────────────────

class _DoAndDontCard extends StatelessWidget {
  final List<String> dos;
  final List<String> donts;

  const _DoAndDontCard({required this.dos, required this.donts});

  @override
  Widget build(BuildContext context) {
    final isMobile = Responsive.isMobile(context);

    final doColumn = _DoColumn(items: dos);
    final dontColumn = _DontColumn(items: donts);

    return SectionCard(
      icon: Icons.rule_rounded,
      iconColor: AppColors.textSecondary,
      iconBg: AppColors.surfacePage,
      title: 'Do & Don\'t',
      subtitle: 'Behavioural guidance from StakeholderPersona + CriticValidator',
      child: isMobile
          ? Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                doColumn,
                AppSpacing.gapMd,
                dontColumn,
              ],
            )
          : Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(child: doColumn),
                AppSpacing.hGapMd,
                Expanded(child: dontColumn),
              ],
            ),
    );
  }
}

class _DoColumn extends StatelessWidget {
  final List<String> items;

  const _DoColumn({required this.items});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.sm, vertical: AppSpacing.xs),
          decoration: BoxDecoration(
            color: AppColors.successLight,
            borderRadius: AppSpacing.roundedSm,
            border: const Border.fromBorderSide(
                BorderSide(color: AppColors.successSubtle)),
          ),
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.check_circle_outline,
                  color: AppColors.success, size: 13),
              SizedBox(width: AppSpacing.xs),
              Text(
                'DO',
                style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w800,
                    color: AppColors.success,
                    letterSpacing: 0.5),
              ),
            ],
          ),
        ),
        AppSpacing.gapSm,
        ...items.map((item) => _DoItem(text: item, isDo: true)),
      ],
    );
  }
}

class _DontColumn extends StatelessWidget {
  final List<String> items;

  const _DontColumn({required this.items});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.sm, vertical: AppSpacing.xs),
          decoration: BoxDecoration(
            color: AppColors.dangerLight,
            borderRadius: AppSpacing.roundedSm,
            border: const Border.fromBorderSide(
                BorderSide(color: AppColors.dangerSubtle)),
          ),
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.cancel_outlined, color: AppColors.danger, size: 13),
              SizedBox(width: AppSpacing.xs),
              Text(
                "DON'T",
                style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w800,
                    color: AppColors.danger,
                    letterSpacing: 0.5),
              ),
            ],
          ),
        ),
        AppSpacing.gapSm,
        ...items.map((item) => _DoItem(text: item, isDo: false)),
      ],
    );
  }
}

class _DoItem extends StatelessWidget {
  final String text;
  final bool isDo;

  const _DoItem({required this.text, required this.isDo});

  @override
  Widget build(BuildContext context) {
    final fg = isDo ? AppColors.success : AppColors.danger;
    final bg = isDo ? AppColors.successLight : AppColors.dangerLight;

    return Container(
      margin: const EdgeInsets.only(bottom: AppSpacing.sm),
      padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.smMd, vertical: AppSpacing.smMd),
      decoration: BoxDecoration(
        color: bg,
        borderRadius: AppSpacing.roundedMd,
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            isDo ? Icons.check_rounded : Icons.close_rounded,
            color: fg,
            size: 14,
          ),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Text(
              text,
              style: TextStyle(
                fontSize: 13,
                color: AppColors.textPrimary,
                height: 1.45,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Next steps ────────────────────────────────────────────────────────────────

class _NextStepsCard extends StatelessWidget {
  final List<String> steps;

  const _NextStepsCard({required this.steps});

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      icon: Icons.check_circle_outline,
      iconColor: AppColors.success,
      iconBg: AppColors.successLight,
      title: 'Next Steps',
      subtitle: '${steps.length} actions to execute after the meeting',
      child: Column(
        children: [
          for (var i = 0; i < steps.length; i++)
            Container(
              margin: const EdgeInsets.only(bottom: AppSpacing.smMd),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: 24,
                    height: 24,
                    decoration: BoxDecoration(
                      color: AppColors.successLight,
                      shape: BoxShape.circle,
                      border: const Border.fromBorderSide(
                          BorderSide(color: AppColors.successSubtle)),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      '${i + 1}',
                      style: const TextStyle(
                          fontSize: 11,
                          fontWeight: FontWeight.w800,
                          color: AppColors.success),
                    ),
                  ),
                  AppSpacing.hGapMd,
                  Expanded(
                    child: Text(
                      steps[i],
                      style: const TextStyle(
                        fontSize: 13,
                        color: AppColors.textPrimary,
                        height: 1.5,
                      ),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}

// ── Agent influence footer ────────────────────────────────────────────────────

class _AgentFooter extends StatelessWidget {
  final SessionResponse session;

  const _AgentFooter({required this.session});

  @override
  Widget build(BuildContext context) {
    final criticRevised = session.agentRuns
        .any((r) => r.agentName == 'FinalSynthesisAgent');

    return Container(
      padding: AppSpacing.cardPaddingLg,
      decoration: AppTheme.heroDecoration,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.account_tree_outlined,
                  color: Colors.white, size: 20),
              AppSpacing.hGapSm,
              Expanded(
                child: Text(
                  'Powered by ${session.agentRuns.length} agents · '
                  '${session.traces.length} influence connections',
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ),
          AppSpacing.gapSm,
          Text(
            criticRevised
                ? 'CriticValidatorAgent identified and corrected 1 unsupported claim. '
                    'Every number in this brief was cross-referenced across all prior agents before delivery. '
                    'Tap "Agent Trace" to see exactly which agent influenced which output.'
                : 'Every recommendation in this brief traces back to research-validated agent outputs. '
                    'Tap "Agent Trace" to see the full influence graph.',
            style: TextStyle(
              color: Colors.white.withValues(alpha: 0.8),
              fontSize: 13,
              height: 1.5,
            ),
          ),
          AppSpacing.gapLg,
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: () => Navigator.pushNamed(
                  context, Routes.trace,
                  arguments: session),
              icon: const Icon(Icons.account_tree_outlined, size: 16),
              label: const Text('View Agent Trace  →  See How Agents Collaborated'),
              style: OutlinedButton.styleFrom(
                foregroundColor: Colors.white,
                side: BorderSide(
                    color: Colors.white.withValues(alpha: 0.5)),
                padding: const EdgeInsets.symmetric(
                    vertical: AppSpacing.smMd, horizontal: AppSpacing.md),
                textStyle: const TextStyle(
                    fontSize: 13, fontWeight: FontWeight.w600),
                minimumSize: const Size(0, 44),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
